server:
  port: 8080
  servlet:
    context-path: /eCommerce

spring:
  application:
    name: eCommerce

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN

jwt:
  signerKey: ${SIGNERKEY:mRZ7rF7uZJ2KQ0Z3V5y9BvJ9P3T8A4XWq6N5C8sYp2A=}

app:
  oauth2:
    redirect:
      frontend-url: ${FRONTEND_URL:http://localhost:5500}